Tests added, coverage test added to GA

diff --git a/.github/workflows/flutter_tests.yml b/.github/workflows/flutter_tests.yml
--- a/.github/workflows/flutter_tests.yml
+++ b/.github/workflows/flutter_tests.yml
@@ -17,17 +17,20 @@ jobs:
       uses: actions/checkout@v3
 
     - name: Cache Flutter dependencies
-      uses: actions/cache@v1
+      uses: actions/cache@v3
       with:
-        path: /opt/hostedtoolcache/flutter
-        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
+        path: |
+          ~/.pub-cache
+          /opt/hostedtoolcache/flutter
+        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
+        restore-keys: |
+          ${{ runner.os }}-flutter-
 
     - name: Set up Flutter
-      if: steps.flutter-cache.outputs.cache-hit != 'true'
       uses: subosito/flutter-action@v2
       with:
-        channel: stable
-        
+        flutter-version: 'stable'
+
     - name: Dart version
       run: dart --version
 
@@ -40,5 +43,37 @@ jobs:
     - name: Install dependencies
       run: flutter pub get
 
-    - name: Run tests
-      run: flutter test
+    - name: Check Dart format
+      run: dart format --set-exit-if-changed .
+      # This will fail the workflow if there are any formatting issues
+
+    - name: Run tests with coverage
+      run: |
+        flutter test --coverage
+        # Generate lcov report
+        genhtml coverage/lcov.info -o coverage/html
+
+    - name: Upload Coverage to Codecov
+      uses: codecov/codecov-action@v3
+      with:
+        files: coverage/lcov.info
+        flags: unittests
+        name: codecov-umbrella
+        fail_ci_if_error: true
+
+    - name: Upload Coverage Report as Artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: coverage-report
+        path: coverage/html
+
+    # Optional: Enforce Coverage Threshold
+    - name: Enforce Coverage Threshold
+      run: |
+        COVERAGE=$(grep -oP '\d+\.\d+' coverage/lcov.info | awk '{s+=$1} END {print s/NR}')
+        echo "Total Coverage: $COVERAGE%"
+        if (( $(echo "$COVERAGE < 40" | bc -l) )); then
+          echo "Coverage is below 40%"
+          exit 1
+        fi
+      shell: bash
